### ISSUE TITLE
Can't find device path for RC522

### ISSUE THREAD

**Issue by deve2ev** [Esamanoaz/NFC-Spotify-Casting#4]
I'm using an NFC module, an RC522.
The device is working when using normal read/write scripts, but doesn't get listed when using lsusb.

**Comment by Esamanoaz** [comment]
Hi deve2ev. I have not run into this issue before. If you can't find another way to see the path of your NFC reader, you can try this out: if you are connecting to the NFC reader over USB, you can set the path variable in the program to just `"usb"` by itself.

The reason for finding the specific path was that, for some people, just `"usb"` didn't work. In your case though, it might be worth trying. Please update me when you try.
